# Generated by Django 2.1.3 on 2018-12-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badJokes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badjokes',
            name='game_round',
            field=models.IntegerField(default=0),
        ),
    ]
