# Generated by Django 2.1.3 on 2018-12-03 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badJokes', '0002_badjokes_game_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='badjokes',
            name='person',
        ),
        migrations.AddField(
            model_name='badjokes',
            name='players',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='badJokes.Players'),
            preserve_default=False,
        ),
    ]
