# Generated by Django 2.1.3 on 2018-12-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badJokes', '0003_auto_20181203_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='photo_link',
            field=models.CharField(default='http://blog.accupass.com/wp-content/uploads/2017/03/1_120122230539_1.jpg', max_length=200),
        ),
    ]
